val simpleData = Seq(("Group A","Section 1",50),("Group B","Section 2", 75), ("Group A", "Section 1", 25))
val simpleRdd = sc.parallelize(simpleData)
val simpleDF = sqlContext.createDataFrame(simpleRdd)
println("Hello Elizabeth")
simpleDF.registerTempTable("SimpleTempTable")
